# Generated by Django 2.2.16 on 2020-09-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200903_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='season_tag', to='home.Episode'),
        ),
    ]
